### ISSUE TITLE
Malformed predicate symbols

### ISSUE THREAD

**Issue by goodmami** [delph-in/erg#1]
In the ERG trunk, from `lexicon.tdl`, there's one remaining malformed surface predicate:

```
 year_in_and_year_out_adv1 := av_-_i-vp-po_le &
  [ ORTH < "year", "in", "and", "year", "out" >,
    SYNSEM [ LKEYS.KEYREL.PRED "_year+in+and+year_out_a_1_rel",
             PHON.ONSET con ] ].
```

The predicate above should have `...year+out...` instead of `...year_out...`.

In the LOGON version there are several more (`_next+door_dir_rel`, `_next+door_state_rel`, `nowhere_near_x_deg_rel`, `_only_child_n_1_rel`, `_pay_per_view_a_1_rel`), but I suppose these have already been fixed (though they still exist in the trunk ERG's `core.smi` file, but that will be regenerated for the new SEM-I format).

**Comment by danflick** [comment]
Okay, I finally fixed this typo in the PRED value for "year in and year out", so it will be in the 2018 stable version.
