### ISSUE TITLE
SF: prop-or-like and PT: notpro in VPM but not SEM-I

### ISSUE THREAD

**Issue by goodmami** [delph-in/erg#13]
The `semi.vpm` has the following under the `PT` variable property:

```
  notpro <> notpro
```

...and the following under the `SF` property:

```
  prop-or-like     <> prop-or-like
```

...meaning that these properties are externally visible (appear on MRSs output by the grammar). However, they are not placed in the value hierarchy in `etc/erg.smi`, so they would be surprising to the user who relies on the SEM-I to understand the semantics. Either they should be added to the SEM-I or we should have `!` on the right-hand-side of those VPM lines.

This is an issue that we discussed over email but never reached a conclusion, although Dan suspected that neither should be externally visible and thus not in the SEM-I.

**Comment by oepen** [comment]
the current trunk looks fine, in this regard.  neither of the above grammar-internal properties should be exposed in external MRSs, the way i read the current VPM.
