### ISSUE TITLE
Only some of the lexical entries in lexicon_rbst are marked _rbst

### ISSUE THREAD

**Issue by fcbond** [delph-in/erg#16]
It is not clear if this is a principled distinction, or if you are meant to look only at the type, ...
e.g. _the_stutter_1_ (for "the the")  but _the_2_rbst_ for ("a the").

**Comment by danflick** [comment]
The names of the relevant lexical entries in lexicon-rbst.tdl have now been made consistent with the convention that each robust entry's name now ends either in _rbst or in _mal.
