### ISSUE TITLE
Bad parse for "What are you holding?"

### ISSUE THREAD

**Issue by EricZinda** [delph-in/erg#20]
using ERG erg-2018-osx-0.9.31.dat and ACE to parse "What are you holding?" on a mac.

One result is this, 
Which has 5 holes: h0, h6, h7, h13, h14
And 6 unassigned handles: h1, h11, h12, h15, h5, h8

The bug is that there is one too few holes.

here's the simple mrs for it:

[ TOP: h0 INDEX: e2 [ e SF: ques ]
RELS: <
[ unknown<0:21> LBL: h1 ARG: x4 [ x PERS: 3 ] ARG0: e2 ]
[ free_relative_q<0:4> LBL: h5 ARG0: x4 RSTR: h6 BODY: h7 ]
[ thing<0:4> LBL: h8 ARG0: x4 ]
[ _be_v_id<5:8> LBL: h8 ARG0: e9 [ e SF: prop TENSE: pres MOOD: indicative PROG: - PERF: - ] ARG1: x4 ARG2: x10 [ x PERS: 2 IND: + PT: std ] ]
[ pron<9:12> LBL: h11 ARG0: x10 ]
[ pronoun_q<9:12> LBL: h12 ARG0: x10 RSTR: h13 BODY: h14 ]
[ _hold_v_1<13:21> LBL: h15 ARG0: e16 [ e SF: prop TENSE: untensed MOOD: indicative PROG: + PERF: - ] ARG1: x4 ARG2: i17 ] >
HCONS: < h0 qeq h1 h6 qeq h8 h13 qeq h11 > ]

**Comment by guyemerson** [comment]
This seems to be an issue with modifying a free relative clause with a gerund.  Presumably, the label of `thing` is not accessible from outside the NP.  Another example, for "whoever sleeps barking naps", where "barking" modifies "whoever sleeps", but the label of `_bark_v_1` is unbound:

[ LTOP: h0
INDEX: e2 [ e SF: prop TENSE: pres MOOD: indicative PROG: - PERF: - ]
RELS: < [ free_relative_ever_q<0:7> LBL: h4 ARG0: x3 [ x PERS: 3 NUM: sg ] RSTR: h5 BODY: h6 ]
 [ person<0:7> LBL: h7 ARG0: x3 ]
 [ _sleep_v_1<8:14> LBL: h7 ARG0: e8 [ e SF: prop TENSE: pres MOOD: indicative PROG: - PERF: - ] ARG1: x3 ]
 [ _bark_v_1<15:22> LBL: h9 ARG0: e10 [ e SF: prop TENSE: untensed MOOD: indicative PROG: + PERF: - ] ARG1: x3 ]
 [ _nap_v_1<23:27> LBL: h1 ARG0: e2 ARG1: x3 ] >
HCONS: < h0 qeq h1 h5 qeq h7 >
ICONS: < > ]

For both of these sentences, there is also a good parse where the gerund and the verb in the free relative clause are linked by a `subord` rel.

**Comment by danflick** [comment]
Yes, the analysis of free relatives is currently flawed in not retaining its nominal relation's label as the LTOP of the phrase so that post-nominal modifiers can constrain it.  The correction will be analogous to what is already done for partitives as in "some that we admired disappeared", but the correction will have to wait for the post-2020 release, alas.

**Comment by danflick** [comment]
Fixed the modification of free relatives, but also corrected the grammar to disallow the first example as a free relative ("What are you holding").  Both corrections in release version 2023.
