### ISSUE TITLE
MRS Generation creates reference to unintroduced e variable for "put the crystal on the table where the safe is."

### ISSUE THREAD

**Issue by EricZinda** [delph-in/erg#21]
The first parse alternative for "put the crystal on the table where the safe is." generates a predicate `loc_nonsp:i21,e22,x16` that references `e22` which isn't introduced by any other predicate.  I believe all variables that are referenced should be introduced by a predicate.

```
                  ┌_crystal_n_1:x8
 _the_q:x8,h11,h12┤
                  │                      ┌_table_n_1:x16
                  │                  ┌and┤
                  │                  │   └loc_nonsp:i21,e22,x16
                  └_the_q:x16,h18,h19┤
                                     │                  ┌_safe_n_1:x24
                                     └_the_q:x24,h25,h26┤
                                                        │                  ┌pron:x3
                                                        └pronoun_q:x3,h5,h6┤
                                                                           └_put_v_1:e2,x3,x8,h9┐
                                                                                                └_on_p_loc:e15,x8,x16
```

TOP: h0 INDEX: e2 [ e SF: comm TENSE: pres MOOD: indicative PROG: - PERF: - ] 
RELS: < 
    [ pronoun_q<0:47> LBL: h4 ARG0: x3 [ x PERS: 2 PT: zero ] RSTR: h5 BODY: h6 ] 
    [ pron<0:47> LBL: h7 ARG0: x3 ] 
    [ _put_v_1<0:3> LBL: h1 ARG0: e2 ARG1: x3 ARG2: x8 [ x PERS: 3 NUM: sg ] ARG3: h9 ] 
    [ _the_q<4:7> LBL: h10 ARG0: x8 RSTR: h11 BODY: h12 ] 
    [ _crystal_n_1<8:15> LBL: h13 ARG0: x8 ] 
    [ _on_p_loc<16:18> LBL: h14 ARG0: e15 [ e SF: prop TENSE: untensed MOOD: indicative PROG: - PERF: - ] ARG1: x8 ARG2: x16 [ x PERS: 3 NUM: sg IND: + ] ] 
    [ _the_q<19:22> LBL: h17 ARG0: x16 RSTR: h18 BODY: h19 ] 
    [ _table_n_1<23:28> LBL: h20 ARG0: x16 ] 
    [ loc_nonsp<29:34> LBL: h20 ARG0: i21 ARG1: e22 [ e SF: prop TENSE: pres MOOD: indicative PROG: - PERF: - ] ARG2: x16 ] 
    [ _the_q<35:38> LBL: h23 ARG0: x24 [ x PERS: 3 NUM: sg IND: + ] RSTR: h25 BODY: h26 ] 
    [ _safe_n_1<39:43> LBL: h27 ARG0: x24 ] > 
HCONS: < h0 qeq h1 h5 qeq h7 h9 qeq h14 h11 qeq h13 h18 qeq h20 h25 qeq h27 > ]

**Comment by danflick** [comment]
This error in the MRS was due to a bug in the lexical type for the relative pronoun "where", now fixed.
