### ISSUE TITLE
erg-2018-osx-0.9.31: "Exit to ..." missing entry for directional preposition

### ISSUE THREAD

**Issue by EricZinda** [delph-in/erg#22]
In erg-2018-osx-0.9.31 phrases with `exit` to like:

`“Exit to Plage”`

generate only stative options like:

`proper_q(x10, named(Plage, x10), pronoun_q(x3, pron(x3), and(_to_p_state(e9, e2, x10), _exit_v_1(e2, x3, i8))))`

A suggested fix is [in this thread](https://delphinqa.ling.washington.edu/t/interpretation-of-on-p-state-for-drop-the-diamond-on-the-table/483/4):

> "the problem with the verb “exit” is that it is currently lacking an entry of the type v_pp_dir_le, for verbs of motion that select for a directional PP (and specialize the PRED name to a directional one). The missing entry is like this:
> exit_v3 := v_pp_dir_le &
> [ ORTH < “exit” >,
> SYNSEM [ LKEYS.KEYREL.PRED “_exit_v_1_rel”,
> PHON.ONSET voc ] ]."

**Comment by danflick** [comment]
Missing entry now added.
