### ISSUE TITLE
There is some wierdness in the example for the left italic marks

### ISSUE THREAD

**Issue by fcbond** [delph-in/erg#23]
For example:
```
w_drop-ileft_plr := %prefix (!f ⌊/!f)
"""
Ignored italics mark affixed     
<ex>catiยฆ
"""
punct_drop_italleft_rule &
 [ RNAME lpxdl ].
```

It would be good to also point to the (or add some) documentation on what the italics marks are.

**Comment by danflick** [comment]
Strange characters in doc string corrected for both left and right italic mark lexical rules.  Also added pointer in doc strings to ErgGml page in DELPH-IN wiki for documentation.
