### ISSUE TITLE
The WN definition "that car is in the wrong traffic lane"

### ISSUE THREAD

**Issue by arademaker** [delph-in/erg#29]
One analysis that LKB gives me:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/86403/144918994-0f16e803-d1e3-4b24-a8a4-e650401dd829.png">

The indexed MRS for this analysis: 

```
<h1,e3:PROP:PRES:INDICATIVE:-:-,
{h4:_that_q_dem<0:4>(x7:3:SG:+, h6, h5),
h8:_car_n_1<5:8>(x7),
h2:ellipsis_ref(e3, x7),
h2:_in_p_state<12:14>(e9:PROP:UNTENSED:INDICATIVE:-:-, e3, x10:3:SG:+),
h11:_the_q<15:18>(x10, h13, h12),
h14:_wrong_a_with<19:24>(e15:PROP:UNTENSED:INDICATIVE:BOOL:-, x10),
h14:compound<25:37>(e17:PROP:UNTENSED:INDICATIVE:-:-, x10, x16:3:SG:-),
h18:udef_q<25:32>(x16, h19, h20),
h21:_traffic_n_1<25:32>(x16),
h14:_lane_n_1<33:37>(x10)},
{h1 qeq h2,h6 qeq h8,h13 qeq h14,h19 qeq h21}>
```

One scoped MRS

```
   _that_q_dem(x7,
	    _car_n_1(x7),
	    _the_q(x10,
		   udef_q(x16, 
			  _traffic_n_1(x16),
			  _wrong_a_with(e15, x10) /\ compound(e17, x10, x16) /\ _lane_n_1(x10)),
		   ellipsis_ref(e3, x7) /\ _in_p_state(e9, e3, x10)))
```

Does it make sense to have a compound split in two different labels (e.g. `h21` and `h14`)? The `udef_q` quantifier restriction shouldn't be `_traffic_n_1(x16) /\  compound(e17, x10, x16) /\ _lane_n_1(x10))`?

**Comment by guyemerson** [comment]
The `compound` relation behaves like an underspecified preposition (see https://github.com/delph-in/docs/wiki/ErgSemantics_Compounding ), and so the labels are different.

But if `udef_q` is interpreted as an existential, then it doesn't really matter in terms of evaluating the MRS -- an existential quantifier is classically interpreted as ∃x R(x)∧B(x).  With that interpretation, your alternative suggestion is not the compositionally derived MRS, but it's logically equivalent.

**Comment by arademaker** [comment]
> With that interpretation, your alternative suggestion is not the compositionally derived MRS

Why? Indeed the generalized existential when converted to the FOL existential will make a conjunction from its RTSR and BODY. But if we have and universal quantifier here the split of the compound would matter. I will read the wiki page, but the splitting of a compound in different label is still confusing go me.

**Comment by guyemerson** [comment]
Consider prepositions, e.g. "Every box on some table is blue".  With explicit quantifiers, we can see that the two nouns have different labels.  The preposition takes the nouns as arguments, and shares a label with one of them.

The ERG analyses compounds so that `compound` and `_on_p` have the same kind of structure, e.g. "boxes on tables are blue", "boxes with tables are blue", "boxes for tables are blue", "table boxes are blue".
