### ISSUE TITLE
Bad analysis for coordinated scopal verbs (disconnected graphs)

### ISSUE THREAD

**Issue by goodmami** [delph-in/erg#3]
Trying to coordinate scopal verbs yields some analyses, but mostly bad ones.

"Abrams hoped and believed it rained." yields 2 analyses in 1214, and 5 in trunk (r25960). The analysis where hoped has no ARG2 (e.g. "Abrams (hoped) and (believed it rained)") seems legit. But there's an analysis where "rain" is not connected to the graph and the QEQs from "hope" and "believed" don't select the label of any EP. There are some other analyses in trunk, but I'm not sure they are useful (2 involve a `u` variable as the ARG1 of the "and").

I came across this when I was trying to get the analysis "Abrams ((hoped and believed) it rained)" to see if hope and believe could share a QEQ or if two QEQs could share a label (lo handle), both of which seem like they would be ill-formed or non-net structures, but also seem like an intuitive way to represent the semantics.

**Comment by danflick** [comment]
In the 2018 version, there are now three analyses for this sentence, each I think defensible, including the one where both "hope" and "believe" have an ARG2 value which is QEQ the label for "rain".  The resulting graph is no longer a tree since two QEQs point to the same node, but it seems like the right semantics.

**Comment by goodmami** [comment]
@danflick Thanks for fixing all these bugs. Regarding this fix, I was testing if having the holes of two EPs qeq to the same label would occur in the ERG because it breaks my encoded assumptions about quantifier scopes. It seems that both PyDelphin and the LKB are able to make DMRSs and EDSs out of the MRS, but when I try to get the "Scoped MRS" from the LKB, it gives me this error:

    make-scoped-mrs(): `Multiple qeqs with right member 13'

Similarly, "Utool MRS" says "MRS structure does not scope", and "FOL approximation" crashes the LKB.

I agree that it seems like the right semantics in terms of the relationships between the semantic entities, but I think this case warrants a bit more discussion, e.g., on the developers list, about whether the MRS formalism is deficient here or if we need an alternative analysis.
