### ISSUE TITLE
[readme.md] dead link

### ISSUE THREAD

**Issue by glenn-slayden** [delph-in/erg#34]
The **readme.md** for delph-in/erg contains a dead link  http://www.delph-in.net/erg/  behind the text "Please see the [ERG website](http://www.delph-in.net/erg/)".

Not sure if this is a temporary outage. The URL is a http 503 for me as of now...

![erg-link-503](https://user-images.githubusercontent.com/5589855/186260399-28cb173a-27c1-48a8-be61-c7a576e420b3.png)

**Comment by oepen** [comment]
i would say this remains a valid ‘landing site’ URL, but we need to update what it redirects to.

i am pretty sure it currently points to a page that used to be hosted at ‘lingo.stanford.edu’ – a server that sadly is no longer there.

my rationale for using concise landing site URLs combined with redirects in the main DELPH-IN web server has always been increased flexibility in moving things around.

in this case, dan should decide what should be the top-level ERG web site these days (maybe ErgTop in the wiki), and i can adjust the redirect accordingly.

**Comment by danflick** [comment]
For now, I've changed the link to point to the Github wiki page ErgTop.  Will revisit as the DELPH-IN doc pages develop further.
