### ISSUE TITLE
disconnected MRS

### ISSUE THREAD

**Issue by arademaker** [delph-in/erg#9]
In the sentence below, see that x3 variable is not the ARG1 of _tie_v_1 as expected. The i9 variable was introduced and the fragment a man is disconnected from the rest of the graph. Is that a bug in the parsers or a problem in the grammar ?? Or maybe none of them ??! :wink:

```
SENT: A man is untying a shoe.
[ LTOP: h0
INDEX: e2 [ e SF: prop TENSE: pres MOOD: indicative PROG: + PERF: - ]
RELS: < [ _a_q<0:1> LBL: h4 ARG0: x3 [ x PERS: 3 NUM: sg IND: + ] RSTR: h5 BODY: h6 ]
 [ _man_n_1<2:5> LBL: h7 ARG0: x3 ]
 [ _tie_v_1<9:16> LBL: h1 ARG0: e8 [ e SF: prop TENSE: pres MOOD: indicative PROG: + PERF: - ] ARG1: i9 ARG2: x10 [ x PERS: 3 NUM: sg IND: + ] ]
 [ _un-_a_rvrs<9:16> LBL: h1 ARG0: e2 ARG1: e8 ]
 [ _a_q<17:18> LBL: h11 ARG0: x10 RSTR: h12 BODY: h13 ]
 [ _shoe_n_1<19:24> LBL: h14 ARG0: x10 ] >
HCONS: < h0 qeq h1 h5 qeq h7 h12 qeq h14 >
ICONS: < > ]
```

This is the output of the trunk version of ERG.

**Comment by guyemerson** [comment]
This is probably a bug in the grammar -- v1214 doesn't seem to have this problem.

**Comment by danflick** [comment]
Yes, this was a bug in the type for verb prefixation lexical rules, which was failing to propagate the XARG of the input lexeme to the output lexeme.  Now fixed, and soon to be checked in to the trunk ERG.
